# Generated by Django 5.1.4 on 2025-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0002_payment_mpesa_receipt_payment_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
